let Villagers = [
	{
		name: "Alice",
		species: "Koala",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Alice_s poster.png",
	},
	{
		name: "Annalisa",
		species: "Anteater",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Annalisa_s poster.png",
	},
	{
		name: "Aurora",
		species: "Penguin",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Aurora_s poster.png",
	},
	{
		name: "Ava",
		species: "Chicken",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ava_s poster.png",
	},
	{
		name: "Bea",
		species: "Dog",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bea_s poster.png",
	},
	{
		name: "Bertha",
		species: "Hippo",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bertha_s poster.png",
	},
	{
		name: "Bettina",
		species: "Mouse",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bettina_s poster.png",
	},
	{
		name: "Cally",
		species: "Squirrel",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cally_s poster.png",
	},
	{
		name: "Caroline",
		species: "Squirrel",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Caroline_s poster.png",
	},
	{
		name: "Carrie",
		species: "Kangaroo",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Carrie_s poster.png",
	},
	{
		name: "Celia",
		species: "Eagle",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Celia_s poster.png",
	},
	{
		name: "Chevre",
		species: "Goat",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chevre_s poster.png",
	},
	{
		name: "Coco",
		species: "Rabbit",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Coco_s poster.png",
	},
	{
		name: "Daisy",
		species: "Dog",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Daisy_s poster.png",
	},
	{
		name: "Deena",
		species: "Duck",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Deena_s poster.png",
	},
	{
		name: "Dora",
		species: "Mouse",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Dora_s poster.png",
	},
	{
		name: "Ellie",
		species: "Elephant",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ellie_s poster.png",
	},
	{
		name: "Eunice",
		species: "Sheep",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Eunice_s poster.png",
	},
	{
		name: "Fauna",
		species: "Deer",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Fauna_s poster.png",
	},
	{
		name: "Flurry",
		species: "Hamster",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Flurry_s poster.png",
	},
	{
		name: "Gala",
		species: "Pig",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gala_s poster.png",
	},
	{
		name: "Gayle",
		species: "Alligator",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gayle_s poster.png",
	},
	{
		name: "Gladys",
		species: "Ostrich",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gladys_s poster.png",
	},
	{
		name: "Goldie",
		species: "Dog",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Goldie_s poster.png",
	},
	{
		name: "Jambette",
		species: "Frog",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jambette_s poster.png",
	},
	{
		name: "June",
		species: "Cub",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-June_s poster.png",
	},
	{
		name: "Kiki",
		species: "Cat",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kiki_s poster.png",
	},
	{
		name: "Kitt",
		species: "Kangaroo",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kitt_s poster.png",
	},
	{
		name: "Lily",
		species: "Frog",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lily_s poster.png",
	},
	{
		name: "Lolly",
		species: "Cat",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lolly_s poster.png",
	},
	{
		name: "Lucy",
		species: "Pig",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lucy_s poster.png",
	},
	{
		name: "Maggie",
		species: "Pig",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Maggie_s poster.png",
	},
	{
		name: "Maple",
		species: "Cub",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Maple_s poster.png",
	},
	{
		name: "Marcie",
		species: "Kangaroo",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Marcie_s poster.png",
	},
	{
		name: "Margie",
		species: "Elephant",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Margie_s poster.png",
	},
	{
		name: "Marina",
		species: "Octopus",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Marina_s poster.png",
	},
	{
		name: "Megan",
		species: "Bear",
		personality: "Normal",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Megan_s poster.png",
	},
	{
		name: "Melba",
		species: "Koala",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Melba_s poster.png",
	},
	{
		name: "Merengue",
		species: "Rhino",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Merengue_s poster.png",
	},
	{
		name: "Midge",
		species: "Bird",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Midge_s poster.png",
	},
	{
		name: "Mitzi",
		species: "Cat",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mitzi_s poster.png",
	},
	{
		name: "Molly",
		species: "Duck",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Molly_s poster.png",
	},
	{
		name: "Nan",
		species: "Goat",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Nan_s poster.png",
	},
	{
		name: "Nana",
		species: "Monkey",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Nana_s poster.png",
	},
	{
		name: "Norma",
		species: "Cow",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Norma_s poster.png",
	},
	{
		name: "Olive",
		species: "Cub",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Olive_s poster.png",
	},
	{
		name: "Peaches",
		species: "Horse",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Peaches_s poster.png",
	},
	{
		name: "Pekoe",
		species: "Cub",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pekoe_s poster.png",
	},
	{
		name: "Poppy",
		species: "Squirrel",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Poppy_s poster.png",
	},
	{
		name: "Rhonda",
		species: "Rhino",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rhonda_s poster.png",
	},
	{
		name: "Sally",
		species: "Squirrel",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sally_s poster.png",
	},
	{
		name: "Sandy",
		species: "Ostrich",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sandy_s poster.png",
	},
	{
		name: "Savannah",
		species: "Horse",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Savannah_s poster.png",
	},
	{
		name: "Skye",
		species: "Wolf",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Skye_s poster.png",
	},
	{
		name: "Stella",
		species: "Sheep",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Stella_s poster.png",
	},
	{
		name: "Sydney",
		species: "Koala",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sydney_s poster.png",
	},
	{
		name: "Sylvana",
		species: "Squirrel",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sylvana_s poster.png",
	},
	{
		name: "Tia",
		species: "Elephant",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tia_s poster.png",
	},
	{
		name: "Vesta",
		species: "Sheep",
		personality: "Normal",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Vesta_s poster.png",
	},
	{
		name: "Agent S",
		species: "Squirrel",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Agent S_s poster.png",
	},
	{
		name: "Anabelle",
		species: "Anteater",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Anabelle_s poster.png",
	},
	{
		name: "Anicotti",
		species: "Mouse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Anicotti_s poster.png",
	},
	{
		name: "Apple",
		species: "Hamster",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Apple_s poster.png",
	},
	{
		name: "Audie",
		species: "Wolf",
		personality: "Peppy",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Audie_s poster.png",
	},
	{
		name: "Bangle",
		species: "Tiger",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bangle_s poster.png",
	},
	{
		name: "Bella",
		species: "Mouse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bella_s poster.png",
	},
	{
		name: "Bianca",
		species: "Tiger",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bianca_s poster.png",
	},
	{
		name: "Bluebear",
		species: "Cub",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bluebear_s poster.png",
	},
	{
		name: "Bonbon",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bonbon_s poster.png",
	},
	{
		name: "Bubbles",
		species: "Hippo",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bubbles_s poster.png",
	},
	{
		name: "Bunnie",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bunnie_s poster.png",
	},
	{
		name: "Candi",
		species: "Mouse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Candi_s poster.png",
	},
	{
		name: "Carmen",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Carmen_s poster.png",
	},
	{
		name: "Cheri",
		species: "Cub",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cheri_s poster.png",
	},
	{
		name: "Chrissy",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chrissy_s poster.png",
	},
	{
		name: "Cookie",
		species: "Dog",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cookie_s poster.png",
	},
	{
		name: "Dotty",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Dotty_s poster.png",
	},
	{
		name: "Felicity",
		species: "Cat",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Felicity_s poster.png",
	},
	{
		name: "Flora",
		species: "Ostrich",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Flora_s poster.png",
	},
	{
		name: "Freckles",
		species: "Duck",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Freckles_s poster.png",
	},
	{
		name: "Gabi",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gabi_s poster.png",
	},
	{
		name: "Ketchup",
		species: "Duck",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ketchup_s poster.png",
	},
	{
		name: "Maddie",
		species: "Dog",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Maddie_s poster.png",
	},
	{
		name: "Merry",
		species: "Cat",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Merry_s poster.png",
	},
	{
		name: "Nibbles",
		species: "Squirrel",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Nibbles_s poster.png",
	},
	{
		name: "Pango",
		species: "Anteater",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pango_s poster.png",
	},
	{
		name: "Pate",
		species: "Duck",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pate_s poster.png",
	},
	{
		name: "Patty",
		species: "Cow",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Patty_s poster.png",
	},
	{
		name: "Peanut",
		species: "Squirrel",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Peanut_s poster.png",
	},
	{
		name: "Peggy",
		species: "Pig",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Peggy_s poster.png",
	},
	{
		name: "Penelope",
		species: "Mouse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Penelope_s poster.png",
	},
	{
		name: "Pinky",
		species: "Bear",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pinky_s poster.png",
	},
	{
		name: "Piper",
		species: "Bird",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Piper_s poster.png",
	},
	{
		name: "Pippy",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pippy_s poster.png",
	},
	{
		name: "Pompom",
		species: "Duck",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pompom_s poster.png",
	},
	{
		name: "Puddles",
		species: "Frog",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Puddles_s poster.png",
	},
	{
		name: "Rosie",
		species: "Cat",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rosie_s poster.png",
	},
	{
		name: "Ruby",
		species: "Rabbit",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ruby_s poster.png",
	},
	{
		name: "Sprinkle",
		species: "Penguin",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sprinkle_s poster.png",
	},
	{
		name: "Tabby",
		species: "Cat",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tabby_s poster.png",
	},
	{
		name: "Tammi",
		species: "Monkey",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tammi_s poster.png",
	},
	{
		name: "Tangy",
		species: "Cat",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tangy_s poster.png",
	},
	{
		name: "Truffles",
		species: "Pig",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Truffles_s poster.png",
	},
	{
		name: "Tutu",
		species: "Bear",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tutu_s poster.png",
	},
	{
		name: "Twiggy",
		species: "Bird",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Twiggy_s poster.png",
	},
	{
		name: "Victoria",
		species: "Horse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Victoria_s poster.png",
	},
	{
		name: "Wendy",
		species: "Sheep",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Wendy_s poster.png",
	},
	{
		name: "Winnie",
		species: "Horse",
		personality: "Peppy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Winnie_s poster.png",
	},
	{
		name: "Agnes",
		species: "Pig",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Agnes_s poster.png",
	},
	{
		name: "Canberra",
		species: "Koala",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Canberra_s poster.png",
	},
	{
		name: "Charlise",
		species: "Bear",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Charlise_s poster.png",
	},
	{
		name: "Cherry",
		species: "Dog",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cherry_s poster.png",
	},
	{
		name: "Deirdre",
		species: "Deer",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Deirdre_s poster.png",
	},
	{
		name: "Diva",
		species: "Frog",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Diva_s poster.png",
	},
	{
		name: "Flo",
		species: "Penguin",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Flo_s poster.png",
	},
	{
		name: "Frita",
		species: "Sheep",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Frita_s poster.png",
	},
	{
		name: "Fuchsia",
		species: "Deer",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Fuchsia_s poster.png",
	},
	{
		name: "Hazel",
		species: "Squirrel",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hazel_s poster.png",
	},
	{
		name: "Katt",
		species: "Cat",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Katt_s poster.png",
	},
	{
		name: "Mira",
		species: "Rabbit",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mira_s poster.png",
	},
	{
		name: "Muffy",
		species: "Sheep",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Muffy_s poster.png",
	},
	{
		name: "Pashmina",
		species: "Goat",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pashmina_s poster.png",
	},
	{
		name: "Paula",
		species: "Bear",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Paula_s poster.png",
	},
	{
		name: "Phoebe",
		species: "Ostrich",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Phoebe_s poster.png",
	},
	{
		name: "Plucky",
		species: "Chicken",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Plucky_s poster.png",
	},
	{
		name: "Reneigh",
		species: "Horse",
		personality: "Sisterly",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Reneigh_s poster.png",
	},
	{
		name: "Renee",
		species: "Rhino",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Renee_s poster.png",
	},
	{
		name: "Rocket",
		species: "Gorilla",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rocket_s poster.png",
	},
	{
		name: "Shari",
		species: "Monkey",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Shari_s poster.png",
	},
	{
		name: "Sylvia",
		species: "Kangaroo",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sylvia_s poster.png",
	},
	{
		name: "Tammy",
		species: "Cub",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tammy_s poster.png",
	},
	{
		name: "Ursala",
		species: "Bear",
		personality: "Sisterly",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ursala_s poster.png",
	},
	{
		name: "Alli",
		species: "Alligator",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Alli_s poster.png",
	},
	{
		name: "Amelia",
		species: "Eagle",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Amelia_s poster.png",
	},
	{
		name: "Ankha",
		species: "Cat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ankha_s poster.png",
	},
	{
		name: "Annalise",
		species: "Horse",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Annalise_s poster.png",
	},
	{
		name: "Astrid",
		species: "Kangaroo",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Astrid_s poster.png",
	},
	{
		name: "Baabara",
		species: "Sheep",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Baabara_s poster.png",
	},
	{
		name: "Becky",
		species: "Chicken",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Becky_s poster.png",
	},
	{
		name: "Bitty",
		species: "Hippo",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bitty_s poster.png",
	},
	{
		name: "Blaire",
		species: "Squirrel",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Blaire_s poster.png",
	},
	{
		name: "Blanche",
		species: "Ostrich",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Blanche_s poster.png",
	},
	{
		name: "Bree",
		species: "Mouse",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bree_s poster.png",
	},
	{
		name: "Broffina",
		species: "Chicken",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Broffina_s poster.png",
	},
	{
		name: "Cashmere",
		species: "Sheep",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cashmere_s poster.png",
	},
	{
		name: "Claudia",
		species: "Tiger",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Claudia_s poster.png",
	},
	{
		name: "Cleo",
		species: "Horse",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cleo_s poster.png",
	},
	{
		name: "Diana",
		species: "Deer",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Diana_s poster.png",
	},
	{
		name: "Elise",
		species: "Monkey",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Elise_s poster.png",
	},
	{
		name: "Eloise",
		species: "Elephant",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Eloise_s poster.png",
	},
	{
		name: "Francine",
		species: "Rabbit",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Francine_s poster.png",
	},
	{
		name: "Freya",
		species: "Wolf",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Freya_s poster.png",
	},
	{
		name: "Friga",
		species: "Penguin",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Friga_s poster.png",
	},
	{
		name: "Gigi",
		species: "Frog",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gigi_s poster.png",
	},
	{
		name: "Gloria",
		species: "Duck",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gloria_s poster.png",
	},
	{
		name: "Greta",
		species: "Mouse",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Greta_s poster.png",
	},
	{
		name: "Gwen",
		species: "Penguin",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gwen_s poster.png",
	},
	{
		name: "Judy",
		species: "Cub",
		personality: "Snooty",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Judy_s poster.png",
	},
	{
		name: "Julia",
		species: "Ostrich",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Julia_s poster.png",
	},
	{
		name: "Kitty",
		species: "Cat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kitty_s poster.png",
	},
	{
		name: "Maelle",
		species: "Duck",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Maelle_s poster.png",
	},
	{
		name: "Mallary",
		species: "Duck",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mallary_s poster.png",
	},
	{
		name: "Mathilda",
		species: "Kangaroo",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mathilda_s poster.png",
	},
	{
		name: "Mint",
		species: "Squirrel",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mint_s poster.png",
	},
	{
		name: "Miranda",
		species: "Duck",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Miranda_s poster.png",
	},
	{
		name: "Monique",
		species: "Cat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Monique_s poster.png",
	},
	{
		name: "Naomi",
		species: "Cow",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Naomi_s poster.png",
	},
	{
		name: "Olivia",
		species: "Cat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Olivia_s poster.png",
	},
	{
		name: "Opal",
		species: "Elephant",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Opal_s poster.png",
	},
	{
		name: "Pancetti",
		species: "Pig",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pancetti_s poster.png",
	},
	{
		name: "Pecan",
		species: "Squirrel",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pecan_s poster.png",
	},
	{
		name: "Portia",
		species: "Dog",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Portia_s poster.png",
	},
	{
		name: "Purrl",
		species: "Cat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Purrl_s poster.png",
	},
	{
		name: "Queenie",
		species: "Ostrich",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Queenie_s poster.png",
	},
	{
		name: "Robin",
		species: "Bird",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Robin_s poster.png",
	},
	{
		name: "Snooty",
		species: "Anteater",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Snooty_s poster.png",
	},
	{
		name: "Soleil",
		species: "Hamster",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Soleil_s poster.png",
	},
	{
		name: "Tasha",
		species: "Squirrel",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tasha_s poster.png",
	},
	{
		name: "Tiffany",
		species: "Rabbit",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tiffany_s poster.png",
	},
	{
		name: "Timbra",
		species: "Sheep",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Timbra_s poster.png",
	},
	{
		name: "Tipper",
		species: "Cow",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tipper_s poster.png",
	},
	{
		name: "Velma",
		species: "Goat",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Velma_s poster.png",
	},
	{
		name: "Violet",
		species: "Gorilla",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Violet_s poster.png",
	},
	{
		name: "Vivian",
		species: "Wolf",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Vivian_s poster.png",
	},
	{
		name: "Whitney",
		species: "Wolf",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Whitney_s poster.png",
	},
	{
		name: "Willow",
		species: "Sheep",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Willow_s poster.png",
	},
	{
		name: "Yuka",
		species: "Koala",
		personality: "Snooty",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Yuka_s poster.png",
	},
	{
		name: "Kabuki",
		species: "Cat",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kabuki_s poster.png",
	},
	{
		name: "Hopper",
		species: "Penguin",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hopper_s poster.png",
	},
	{
		name: "Ike",
		species: "Bear",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ike_s poster.png",
	},
	{
		name: "Gonzo",
		species: "Koala",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gonzo_s poster.png",
	},
	{
		name: "Gaston",
		species: "Rabbit",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gaston_s poster.png",
	},
	{
		name: "Gruff",
		species: "Goat",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Gruff_s poster.png",
	},
	{
		name: "Groucho",
		species: "Bear",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Groucho_s poster.png",
	},
	{
		name: "Grizzly",
		species: "Bear",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Grizzly_s poster.png",
	},
	{
		name: "Hamphrey",
		species: "Hamster",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hamphrey_s poster.png",
	},
	{
		name: "Harry",
		species: "Hippo",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Harry_s poster.png",
	},
	{
		name: "Dobie",
		species: "Wolf",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Dobie_s poster.png",
	},
	{
		name: "Curt",
		species: "Bear",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Curt_s poster.png",
	},
	{
		name: "Croque",
		species: "Frog",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Croque_s poster.png",
	},
	{
		name: "Cyrano",
		species: "Anteater",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cyrano_s poster.png",
	},
	{
		name: "Cyd",
		species: "Elephant",
		personality: "Cranky",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Cyd_s poster.png",
	},
	{
		name: "Del",
		species: "Alligator",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Del_s poster.png",
	},
	{
		name: "Fang",
		species: "Wolf",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Fang_s poster.png",
	},
	{
		name: "Elvis",
		species: "Lion",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Elvis_s poster.png",
	},
	{
		name: "Frank",
		species: "Eagle",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Frank_s poster.png",
	},
	{
		name: "Angus",
		species: "Bull",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Angus_s poster.png",
	},
	{
		name: "Admiral",
		species: "Bird",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Admiral_s poster.png",
	},
	{
		name: "Apollo",
		species: "Eagle",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Apollo_s poster.png",
	},
	{
		name: "Avery",
		species: "Eagle",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Avery_s poster.png",
	},
	{
		name: "Camofrog",
		species: "Frog",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Camofrog_s poster.png",
	},
	{
		name: "Butch",
		species: "Dog",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Butch_s poster.png",
	},
	{
		name: "Buzz",
		species: "Eagle",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Buzz_s poster.png",
	},
	{
		name: "Boris",
		species: "Pig",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Boris_s poster.png",
	},
	{
		name: "Boyd",
		species: "Gorilla",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Boyd_s poster.png",
	},
	{
		name: "Bruce",
		species: "Deer",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bruce_s poster.png",
	},
	{
		name: "Chow",
		species: "Bear",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chow_s poster.png",
	},
	{
		name: "Chief",
		species: "Wolf",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chief_s poster.png",
	},
	{
		name: "Cesar",
		species: "Gorilla",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cesar_s poster.png",
	},
	{
		name: "Peewee",
		species: "Gorilla",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Peewee_s poster.png",
	},
	{
		name: "Octavian",
		species: "Octopus",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Octavian_s poster.png",
	},
	{
		name: "Murphy",
		species: "Cub",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Murphy_s poster.png",
	},
	{
		name: "Limberg",
		species: "Mouse",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Limberg_s poster.png",
	},
	{
		name: "Lobo",
		species: "Wolf",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lobo_s poster.png",
	},
	{
		name: "Knox",
		species: "Chicken",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Knox_s poster.png",
	},
	{
		name: "Monty",
		species: "Monkey",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Monty_s poster.png",
	},
	{
		name: "Static",
		species: "Squirrel",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Static_s poster.png",
	},
	{
		name: "Spike",
		species: "Rhino",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Spike_s poster.png",
	},
	{
		name: "Ricky",
		species: "Squirrel",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ricky_s poster.png",
	},
	{
		name: "Rasher",
		species: "Pig",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rasher_s poster.png",
	},
	{
		name: "Rizzo",
		species: "Mouse",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rizzo_s poster.png",
	},
	{
		name: "Rocco",
		species: "Hippo",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rocco_s poster.png",
	},
	{
		name: "Rolf",
		species: "Tiger",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rolf_s poster.png",
	},
	{
		name: "Rooney",
		species: "Kangaroo",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rooney_s poster.png",
	},
	{
		name: "Roscoe",
		species: "Horse",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Roscoe_s poster.png",
	},
	{
		name: "Tom",
		species: "Cat",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tom_s poster.png",
	},
	{
		name: "T-Bone",
		species: "Bull",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-T-Bone_s poster.png",
	},
	{
		name: "Vladimir",
		species: "Cub",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Vladimir_s poster.png",
	},
	{
		name: "Vic",
		species: "Bull",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Vic_s poster.png",
	},
	{
		name: "Wart Jr",
		species: "Frog",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Wart jr._s poster.png",
	},
	{
		name: "Walt",
		species: "Kangaroo",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Walt_s poster.png",
	},
	{
		name: "Wolfgang",
		species: "Wolf",
		personality: "Cranky",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Wolfgang_s poster.png",
	},
	{
		name: "Jitters",
		species: "Bird",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jitters_s poster.png",
	},
	{
		name: "Jay",
		species: "Bird",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jay_s poster.png",
	},
	{
		name: "Iggly",
		species: "Penguin",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Iggly_s poster.png",
	},
	{
		name: "Genji",
		species: "Rabbit",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Genji_s poster.png",
	},
	{
		name: "Frobert",
		species: "Frog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Frobert_s poster.png",
	},
	{
		name: "Goose",
		species: "Chicken",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Goose_s poster.png",
	},
	{
		name: "Hamlet",
		species: "Hamster",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hamlet_s poster.png",
	},
	{
		name: "Dom",
		species: "Sheep",
		personality: "Jock",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Dom_s poster.png",
	},
	{
		name: "Curly",
		species: "Pig",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Curly_s poster.png",
	},
	{
		name: "Drift",
		species: "Frog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Drift_s poster.png",
	},
	{
		name: "Flip",
		species: "Monkey",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Flip_s poster.png",
	},
	{
		name: "Biff",
		species: "Hippo",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Biff_s poster.png",
	},
	{
		name: "Bill",
		species: "Duck",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bill_s poster.png",
	},
	{
		name: "Billy",
		species: "Goat",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Billy_s poster.png",
	},
	{
		name: "Bam",
		species: "Deer",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bam_s poster.png",
	},
	{
		name: "Antonio",
		species: "Anteater",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Antonio_s poster.png",
	},
	{
		name: "Axel",
		species: "Elephant",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Axel_s poster.png",
	},
	{
		name: "Bud",
		species: "Lion",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bud_s poster.png",
	},
	{
		name: "Buck",
		species: "Horse",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Buck_s poster.png",
	},
	{
		name: "Boots",
		species: "Alligator",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Boots_s poster.png",
	},
	{
		name: "Boone",
		species: "Gorilla",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Boone_s poster.png",
	},
	{
		name: "Cobb",
		species: "Pig",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cobb_s poster.png",
	},
	{
		name: "Coach",
		species: "Bull",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Coach_s poster.png",
	},
	{
		name: "Cousteau",
		species: "Frog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cousteau_s poster.png",
	},
	{
		name: "Poncho",
		species: "Cub",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Poncho_s poster.png",
	},
	{
		name: "Peck",
		species: "Bird",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Peck_s poster.png",
	},
	{
		name: "Pierce",
		species: "Eagle",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pierce_s poster.png",
	},
	{
		name: "Mott",
		species: "Lion",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mott_s poster.png",
	},
	{
		name: "Mac",
		species: "Dog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Mac_s poster.png",
	},
	{
		name: "Lyman",
		species: "Koala",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lyman_s poster.png",
	},
	{
		name: "Louie",
		species: "Gorilla",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Louie_s poster.png",
	},
	{
		name: "Kevin",
		species: "Pig",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kevin_s poster.png",
	},
	{
		name: "Kid Cat",
		species: "Cat",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kid Cat_s poster.png",
	},
	{
		name: "Kody",
		species: "Cub",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kody_s poster.png",
	},
	{
		name: "Leonardo",
		species: "Tiger",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Leonardo_s poster.png",
	},
	{
		name: "Moose",
		species: "Mouse",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Moose_s poster.png",
	},
	{
		name: "Sprocket",
		species: "Ostrich",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sprocket_s poster.png",
	},
	{
		name: "Sparro",
		species: "Bird",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sparro_s poster.png",
	},
	{
		name: "Sly",
		species: "Alligator",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sly_s poster.png",
	},
	{
		name: "Snake",
		species: "Rabbit",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Snake_s poster.png",
	},
	{
		name: "Samson",
		species: "Mouse",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Samson_s poster.png",
	},
	{
		name: "Rudy",
		species: "Cat",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rudy_s poster.png",
	},
	{
		name: "Rowan",
		species: "Tiger",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rowan_s poster.png",
	},
	{
		name: "Scoot",
		species: "Duck",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Scoot_s poster.png",
	},
	{
		name: "Sheldon",
		species: "Squirrel",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sheldon_s poster.png",
	},
	{
		name: "Ribbot",
		species: "Frog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ribbot_s poster.png",
	},
	{
		name: "Rod",
		species: "Mouse",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rod_s poster.png",
	},
	{
		name: "Roald",
		species: "Penguin",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Roald_s poster.png",
	},
	{
		name: "Rory",
		species: "Lion",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rory_s poster.png",
	},
	{
		name: "Tank",
		species: "Rhino",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tank_s poster.png",
	},
	{
		name: "Teddy",
		species: "Bear",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Teddy_s poster.png",
	},
	{
		name: "Sterling",
		species: "Eagle",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Sterling_s poster.png",
	},
	{
		name: "Stinky",
		species: "Cat",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Stinky_s poster.png",
	},
	{
		name: "Tad",
		species: "Frog",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tad_s poster.png",
	},
	{
		name: "Tybalt",
		species: "Tiger",
		personality: "Jock",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tybalt_s poster.png",
	},
	{
		name: "Jeremiah",
		species: "Frog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jeremiah_s poster.png",
	},
	{
		name: "Joey",
		species: "Duck",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Joey_s poster.png",
	},
	{
		name: "Hornsby",
		species: "Rhino",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hornsby_s poster.png",
	},
	{
		name: "Hopkins",
		species: "Rabbit",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hopkins_s poster.png",
	},
	{
		name: "Hugh",
		species: "Pig",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hugh_s poster.png",
	},
	{
		name: "Jacob",
		species: "Bird",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jacob_s poster.png",
	},
	{
		name: "Drake",
		species: "Duck",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Drake_s poster.png",
	},
	{
		name: "Drago",
		species: "Alligator",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Drago_s poster.png",
	},
	{
		name: "Doc",
		species: "Rabbit",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Doc_s poster.png",
	},
	{
		name: "Derwin",
		species: "Duck",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Derwin_s poster.png",
	},
	{
		name: "Deli",
		species: "Monkey",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Deli_s poster.png",
	},
	{
		name: "Dizzy",
		species: "Elephant",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Dizzy_s poster.png",
	},
	{
		name: "Cranston",
		species: "Ostrich",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cranston_s poster.png",
	},
	{
		name: "Cube",
		species: "Penguin",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cube_s poster.png",
	},
	{
		name: "Erik",
		species: "Deer",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Erik_s poster.png",
	},
	{
		name: "Egbert",
		species: "Chicken",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Egbert_s poster.png",
	},
	{
		name: "Elmer",
		species: "Horse",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Elmer_s poster.png",
	},
	{
		name: "Filbert",
		species: "Squirrel",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Filbert_s poster.png",
	},
	{
		name: "Bob",
		species: "Cat",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bob_s poster.png",
	},
	{
		name: "Biskit",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Biskit_s poster.png",
	},
	{
		name: "Big Top",
		species: "Elephant",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Big Top_s poster.png",
	},
	{
		name: "Barold",
		species: "Cub",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Barold_s poster.png",
	},
	{
		name: "Beau",
		species: "Deer",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Beau_s poster.png",
	},
	{
		name: "Benedict",
		species: "Chicken",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Benedict_s poster.png",
	},
	{
		name: "Benjamin",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Benjamin_s poster.png",
	},
	{
		name: "Anchovy",
		species: "Bird",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Anchovy_s poster.png",
	},
	{
		name: "Al",
		species: "Gorilla",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Al_s poster.png",
	},
	{
		name: "Alfonso",
		species: "Alligator",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Alfonso_s poster.png",
	},
	{
		name: "Bones",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Bones_s poster.png",
	},
	{
		name: "Boomer",
		species: "Penguin",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Boomer_s poster.png",
	},
	{
		name: "Broccolo",
		species: "Mouse",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Broccolo_s poster.png",
	},
	{
		name: "Chester",
		species: "Cub",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chester_s poster.png",
	},
	{
		name: "Clyde",
		species: "Horse",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Clyde_s poster.png",
	},
	{
		name: "Clay",
		species: "Hamster",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Clay_s poster.png",
	},
	{
		name: "Claude",
		species: "Rabbit",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Claude_s poster.png",
	},
	{
		name: "Cole",
		species: "Cat",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Cole_s poster.png",
	},
	{
		name: "Punchy",
		species: "Cat",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Punchy_s poster.png",
	},
	{
		name: "Pudge",
		species: "Cub",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pudge_s poster.png",
	},
	{
		name: "Puck",
		species: "Penguin",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Puck_s poster.png",
	},
	{
		name: "Prince",
		species: "Frog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Prince_s poster.png",
	},
	{
		name: "Nate",
		species: "Bear",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Nate_s poster.png",
	},
	{
		name: "Ozzie",
		species: "Koala",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ozzie_s poster.png",
	},
	{
		name: "Papi",
		species: "Horse",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Papi_s poster.png",
	},
	{
		name: "Paolo",
		species: "Elephant",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Paolo_s poster.png",
	},
	{
		name: "Lucky",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lucky_s poster.png",
	},
	{
		name: "Marcel",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Marcel_s poster.png",
	},
	{
		name: "Moe",
		species: "Cat",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Moe_s poster.png",
	},
	{
		name: "Spork",
		species: "Pig",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Spork_s poster.png",
	},
	{
		name: "Simon",
		species: "Monkey",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Simon_s poster.png",
	},
	{
		name: "Sherb",
		species: "Goat",
		personality: "Lazy",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Sherb_s poster.png",
	},
	{
		name: "Rex",
		species: "Lion",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rex_s poster.png",
	},
	{
		name: "Raddle",
		species: "Frog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Raddle_s poster.png",
	},
	{
		name: "Rodeo",
		species: "Bull",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rodeo_s poster.png",
	},
	{
		name: "Stu",
		species: "Bull",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Stu_s poster.png",
	},
	{
		name: "Stitches",
		species: "Cub",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Stitches_s poster.png",
	},
	{
		name: "Tucker",
		species: "Elephant",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tucker_s poster.png",
	},
	{
		name: "Weber",
		species: "Duck",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Weber_s poster.png",
	},
	{
		name: "Wade",
		species: "Penguin",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Wade_s poster.png",
	},
	{
		name: "Walker",
		species: "Dog",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Walker_s poster.png",
	},
	{
		name: "Zucker",
		species: "Octopus",
		personality: "Lazy",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Zucker_s poster.png",
	},
	{
		name: "Ken",
		species: "Chicken",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ken_s poster.png",
	},
	{
		name: "Keaton",
		species: "Eagle",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Keaton_s poster.png",
	},
	{
		name: "Julian",
		species: "Horse",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Julian_s poster.png",
	},
	{
		name: "Huck",
		species: "Frog",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Huck_s poster.png",
	},
	{
		name: "Henry",
		species: "Frog",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Henry_s poster.png",
	},
	{
		name: "Hippeux",
		species: "Hippo",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hippeux_s poster.png",
	},
	{
		name: "Jacques",
		species: "Bird",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Jacques_s poster.png",
	},
	{
		name: "Graham",
		species: "Hamster",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Graham_s poster.png",
	},
	{
		name: "Hans",
		species: "Gorilla",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Hans_s poster.png",
	},
	{
		name: "Curlos",
		species: "Sheep",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Curlos_s poster.png",
	},
	{
		name: "Eugene",
		species: "Koala",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Eugene_s poster.png",
	},
	{
		name: "Ed",
		species: "Horse",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Ed_s poster.png",
	},
	{
		name: "Beardo",
		species: "Bear",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Beardo_s poster.png",
	},
	{
		name: "Chops",
		species: "Pig",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chops_s poster.png",
	},
	{
		name: "Chadder",
		species: "Mouse",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Chadder_s poster.png",
	},
	{
		name: "Colton",
		species: "Horse",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Colton_s poster.png",
	},
	{
		name: "Phil",
		species: "Ostrich",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Phil_s poster.png",
	},
	{
		name: "Pietro",
		species: "Sheep",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Pietro_s poster.png",
	},
	{
		name: "Olaf",
		species: "Anteater",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Olaf_s poster.png",
	},
	{
		name: "O'Hare",
		species: "Rabbit",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-O_hare_s poster.png",
	},
	{
		name: "Lucha",
		species: "Bird",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lucha_s poster.png",
	},
	{
		name: "Lionel",
		species: "Lion",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lionel_s poster.png",
	},
	{
		name: "Lopez",
		species: "Deer",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Lopez_s poster.png",
	},
	{
		name: "Kidd",
		species: "Goat",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kidd_s poster.png",
	},
	{
		name: "Klaus",
		species: "Bear",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Klaus_s poster.png",
	},
	{
		name: "Kyle",
		species: "Wolf",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Kyle_s poster.png",
	},
	{
		name: "Leopold",
		species: "Lion",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Leopold_s poster.png",
	},
	{
		name: "Marshal",
		species: "Squirrel",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Marshal_s poster.png",
	},
	{
		name: "Shep",
		species: "Dog",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Shep_s poster.png",
	},
	{
		name: "Quillson",
		species: "Duck",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Quillson_s poster.png",
	},
	{
		name: "Raymond",
		species: "Cat",
		personality: "Smug",
		amiibo: false,
		poster: "VillagerPosters/NH-Poster-Raymond_s poster.png",
	},
	{
		name: "Rodney",
		species: "Hamster",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Rodney_s poster.png",
	},
	{
		name: "Tex",
		species: "Penguin",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Tex_s poster.png",
	},
	{
		name: "Zell",
		species: "Deer",
		personality: "Smug",
		amiibo: true,
		poster: "VillagerPosters/NH-Poster-Zell_s poster.png",
	},
];

export default Villagers;
